// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBprRHm3S1n98Bcan-dHdpCgf3B6ID-4uA',
    appId: '1:614715264426:android:36c0f813e1e81c548a2fd3',
    messagingSenderId: '614715264426',
    projectId: 'exam4-dd04d',
    storageBucket: 'exam4-dd04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV16CdqallOyhzcvACUBlAJDRADl5oX4A',
    appId: '1:614715264426:ios:baa982faebec97708a2fd3',
    messagingSenderId: '614715264426',
    projectId: 'exam4-dd04d',
    storageBucket: 'exam4-dd04d.appspot.com',
    iosBundleId: 'com.example.exam4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV16CdqallOyhzcvACUBlAJDRADl5oX4A',
    appId: '1:614715264426:ios:e4f42029e1d1c26f8a2fd3',
    messagingSenderId: '614715264426',
    projectId: 'exam4-dd04d',
    storageBucket: 'exam4-dd04d.appspot.com',
    iosBundleId: 'com.example.exam4.RunnerTests',
  );
}
